---
- name: Docker postgres prepare
  hosts: all
  become: true

  tasks:
    - name: Check postgres_data_dir exists
      stat:
        path: "{{ postgres_data_dir }}"
      register: postgres_data_dir_stat

    - name: Ensure postgres_data_dir exists
      file:
        state: directory
        path: "{{ postgres_data_dir }}"
        group: "docker"
        mode: 0775
      when: not postgres_data_dir_stat.stat.exists

    - name: Ensure postgres_log_dir exists
      file:
        state: directory
        path: "{{ postgres_log_dir }}"
        group: "docker"
        mode: 0777

    - name: Ensure postgres_dotenv_dir exists
      file:
        state: directory
        path: "{{ postgres_dotenv_dir }}"
        mode: 0755

    - name: Touch .env
      file:
        path: "{{ postgres_dotenv_dir }}/.env"
        state: touch
        mode: 0644
        access_time: preserve
        modification_time: preserve

    - name: Update .env
      lineinfile:
        path: "{{ postgres_dotenv_dir }}/.env"
        regexp: "^{{ item.key }}="
        line: '{{ item.key }}={{ item.value }}'
      with_items:
        - key: "POSTGRES_PORT"
          value: "{{ postgres_port }}"
        - key: "POSTGRES_DATABASE"
          value: "{{ postgres_database }}"
        - key: "POSTGRES_USER"
          value: "{{ postgres_user }}"
        - key: "POSTGRES_PASSWORD"
          value: "{{ postgres_password }}"
        - key: "POSTGRES_DATA_DIR"
          value: "{{ postgres_data_dir }}"
        - key: "POSTGRES_LOG_DIR"
          value: "{{ postgres_log_dir }}"

    - name: Touch postgresql.conf
      file:
        path: "{{ postgres_data_dir }}/postgresql.conf"
        state: touch
        mode: 0644
        access_time: preserve
        modification_time: preserve

    - name: Update postgresql.conf
      lineinfile:
        path: "{{ postgres_data_dir }}/postgresql.conf"
        regexp: "^{{ item.key }}[\\s]*="
        line: '{{ item.key }} = {{ item.value }}'
      with_items:
        - key: "listen_addresses"
          value: "'*'"
        - key: "external_pid_file"
          value: "'/var/run/postgresql/postgresql.pid'"
        - key: "log_destination"
          value: "'stderr'"
        - key: "logging_collector"
          value: "on"
        - key: "log_directory"
          value: "'/var/log/postgresql'"
        - key: "log_filename"
          value: "'postgresql.log'"
