version: '3'

services:
  postgres:
    image: "${POSTGRES_DOCKER_TAG:-postgres:11.1-alpine}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-db}
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data/db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}", "${POSTGRES_DATABASE:-db}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
    pid: host
    ports:
      - "${POSTGRES_PORT:-5432}:5432/tcp"
    networks:
      - postgres

volumes:
  postgres_data:

networks:
  postgres:
